#!/usr/bin/env python3
"""Generate the site's Markdown pages and the assessment data from data/*.yml.

The data files under data/ are the single source of truth. This script renders:

  * one page per template            -> docs/<section>/<page>.md
  * one index page per section       -> docs/<section>/index.md
  * the EU AI Act readiness checklist -> generated from questions.yml
  * the assessment app's data        -> docs/assess/assessment-data.json
  * the navigation block             -> mkdocs.yml (between NAV markers)

Every generated file carries a "do not edit" header. CI re-runs this script and
fails if the working tree changed, so a hand-edit of a generated page is caught
loudly instead of being silently overwritten on the next build.

Usage:
    python tools/build_content.py            # write files
    python tools/build_content.py --check    # verify only; non-zero if stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DOCS = ROOT / "docs"

BANNER = (
    "<!-- GENERATED FILE — DO NOT EDIT.\n"
    "     Source: data/{source}\n"
    "     Regenerate with: python tools/build_content.py -->\n\n"
)

NAV_START = "# NAV:START (generated by tools/build_content.py - do not edit by hand)"
NAV_END = "# NAV:END"

STATUS_LABELS = {"ready": "Ready", "draft": "Draft", "stub": "Stub"}

# Template ids that also get an .xlsx. Populated from data/spreadsheets.yml at
# runtime so the download buttons cannot advertise a file that is not built.
SPREADSHEET_IDS = set()

# Order categories appear in the questionnaire and the report.
CATEGORY_ORDER = [
    "Inventory",
    "Risk",
    "Documentation",
    "Oversight",
    "Transparency",
    "Third-party",
    "Literacy",
]

# Readiness bands, shared by the report and the checklist page.
#
# The thresholds and labels come from data/benchmarks.yml, which also records
# WHY each one sits where it does. Keeping the numbers in one place means the
# published explanation cannot drift from the scoring the tool actually applies.
BAND_BLURBS = {
    "Advanced": "Controls are measured and independently assured. Focus on continuous improvement.",
    "Established": "The core is in place and operating. Focus on evidencing that controls work.",
    "Developing": "Foundations exist but coverage is uneven. Close the documentation and process gaps.",
    "Early": "Significant exposure. Start with inventory, prohibited-practice screening, and accountability.",
}


def load(name: str):
    with open(DATA / name, encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def rel_link(from_path: str, to_path: str) -> str:
    """Relative link from one docs page to another, MkDocs-style."""
    from_dir = Path(from_path).parent
    return Path(__import__("os").path.relpath(Path(to_path), from_dir)).as_posix()


def resolve_defaults(text: str) -> str:
    """Replace {{default:id}} with the recommendation and its deviation rule.

    A bracketed placeholder delegates a decision to the reader. These render as
    a stated value plus the condition for changing it, so accepting the default
    is an informed choice rather than a shrug.
    """
    if not text:
        return text

    def sub(match: re.Match) -> str:
        did = match.group(1).strip()
        d = DEFAULTS.get(did)
        if d is None:
            raise SystemExit(
                f"ERROR: unknown default id '{{{{default:{did}}}}}'. "
                f"Known: {sorted(DEFAULTS)}"
            )
        return (
            f'<span class="gk-default" title="{esc_attr(d["why"])}">'
            f'<strong>{d["value"]}</strong>'
            f'<span class="gk-default-unless">Unless: '
            f'{" ".join(d["unless"].split())}</span></span>'
        )

    return re.sub(r"\{\{default:([a-z0-9\-]+)\}\}", sub, text)


def esc_attr(s: str) -> str:
    return " ".join(str(s).split()).replace('"', "&quot;").replace("<", "&lt;")


def resolve_links(text: str, from_path: str, by_id: dict) -> str:
    """Replace {{template-id}} with a proper relative Markdown link.

    Keeping cross-references as ids means a page can be moved by changing its
    `path` in the data file without producing a single broken link.
    """
    if not text:
        return text

    text = resolve_defaults(text)

    def sub(match: re.Match) -> str:
        tid = match.group(1).strip()
        target = by_id.get(tid)
        if target is None:
            raise SystemExit(
                f"ERROR: unknown template id '{{{{{tid}}}}}' referenced from {from_path}"
            )
        return f"[{target['title']}]({rel_link(from_path, target['path'])})"

    return re.sub(r"\{\{([a-z0-9\-]+)\}\}", sub, text)


def status_pill(status: str) -> str:
    return f'<span class="pill {status}">{STATUS_LABELS[status]}</span>'


def build_checklist_body(questions: list, templates_by_id: dict, page_path: str) -> str:
    """Render the 25-point checklist FROM the question bank.

    This is why the published checklist and the assessment tool cannot drift:
    both read the same list.
    """
    items = sorted(
        [q for q in questions if q.get("checklist")], key=lambda q: q["checklist"]
    )
    groups: dict[str, list] = {}
    for q in items:
        groups.setdefault(q["category"], []).append(q)

    out = [
        "This checklist is generated from the same question bank as the "
        "[interactive assessment](" + rel_link(page_path, "assess/index.md") + "), "
        "so the two can never disagree.\n",
        "**Tick the boxes as you go** — your progress is saved in this browser "
        "and nothing is uploaded.\n",
        # docs/assess/checklist.js finds this element, enables the checkboxes,
        # and renders the live count and clear control into it.
        '<div id="gk-checklist" class="gk-cl"></div>\n',
    ]

    for category in CATEGORY_ORDER:
        if category not in groups:
            continue
        out.append(f"### {category}\n")
        for q in groups[category]:
            n = q["checklist"]
            out.append(f"- [ ] **{n}.** {q['text']}")
            out.append(f"    <br><small>{q['help'].strip()}</small>")
            if q.get("evidence"):
                out.append(
                    "    <br><small class=\"gk-ev\">**Evidence:** "
                    + " ".join(q["evidence"].split()) + "</small>"
                )
            tpl = [templates_by_id[t] for t in q.get("templates", []) if t in templates_by_id]
            if tpl:
                links = " · ".join(
                    f"[{t['title']}]({rel_link(page_path, t['path'])})" for t in tpl[:3]
                )
                out.append(f"    <br><small>**Fix with:** {links}</small>")
            out.append("")

    out.append("---\n")
    out.append("### Turn gaps into action\n")
    out.append(
        "Every unticked item maps to something in this kit. For a scored, "
        "role-specific version of this checklist — with a report you can present "
        "to a board or a regulator — take the "
        f"[interactive assessment]({rel_link(page_path, 'assess/index.md')}). "
        "Your answers stay in your browser.\n"
    )
    return "\n".join(out)


def render_template_page(t: dict, by_id: dict, snippets: dict, questions: list) -> str:
    path = t["path"]
    parts = [BANNER.format(source="templates.yml")]
    parts.append(f"# {t['title']}\n")

    # Status pill, plus review metadata where a page carries it. Time-sensitive
    # pages say when they were last checked, so a reader can judge staleness
    # rather than assume currency.
    meta = [status_pill(t["status"])]
    if t.get("version"):
        meta.append(f'<span class="gk-meta">v{t["version"]}</span>')
    if t.get("reviewed"):
        meta.append(
            f'<span class="gk-meta">Last reviewed <strong>{t["reviewed"]}</strong></span>'
        )
    parts.append(" &nbsp;·&nbsp; ".join(meta) + "\n")

    if t["status"] == "stub":
        parts.append(
            snippets["stub_invite"].format(contributing=rel_link(path, "contributing.md"))
        )
    elif t["status"] == "draft":
        parts.append(
            snippets["draft_note"].format(contributing=rel_link(path, "contributing.md"))
        )

    # Download buttons. build_downloads.py writes one .docx per template and a
    # .xlsx for anything in spreadsheets.yml; these links must match its output.
    dl = rel_link(path, "downloads/x").rsplit("/", 1)[0]
    buttons = [
        f'[:material-file-word: Word]({dl}/{t["id"]}.docx)'
        '{ .md-button .gk-dl download }'
    ]
    if t["id"] in SPREADSHEET_IDS:
        buttons.append(
            f'[:material-file-excel: Excel]({dl}/{t["id"]}.xlsx)'
            '{ .md-button .gk-dl download }'
        )
    buttons.append(
        f'[:material-language-markdown: Markdown]({dl}/{t["id"]}.md.txt)'
        f'{{ .md-button .gk-dl download="{t["id"]}.md" }}'
    )
    parts.append('<div class="gk-downloads" markdown>\n'
                 + "\n".join(buttons) + "\n</div>\n")

    ex = EXAMPLE_OF.get(t["id"])
    if ex:
        parts.append(
            f'!!! example "See this filled in"\n'
            f"    A [worked example]({rel_link(path, ex['path'])}) shows this\n"
            f"    template completed for a fictional mid-size company.\n"
        )

    parts.append(f"**Purpose.** {resolve_links(t['purpose'].strip(), path, by_id)}\n")
    parts.append(f"**When to use it.** {resolve_links(t['when_to_use'].strip(), path, by_id)}\n")
    parts.append(f"**How to use it.** {resolve_links(t['how_to_use'].strip(), path, by_id)}\n")

    # Which assessment questions this template answers — generated, so adding a
    # question automatically surfaces it on the pages that fix it.
    related_qs = [q for q in questions if t["id"] in q.get("templates", [])]
    if related_qs:
        qlist = ", ".join(f"**{q['id']}**" for q in related_qs[:8])
        parts.append(
            f"!!! tip \"Closes assessment gaps\"\n"
            f"    This template addresses {qlist} in the "
            f"[readiness assessment]({rel_link(path, 'assess/index.md')}).\n"
        )

    # Editable register, for the templates people actually work IN rather than
    # read. Collapsed by default so it never buries the template itself.
    if t["id"] in SPREADSHEET_IDS:
        parts.append("---\n")
        parts.append('## Fill it in here\n')
        parts.append(
            "Work directly in the browser — nothing is uploaded, and your rows "
            "are saved on this device. Download to Excel whenever you want, or "
            "save a file you can reopen later.\n"
        )
        # NOTE: this is a raw HTML attribute, so MkDocs does NOT rewrite it the
        # way it rewrites Markdown links. rel_link() is relative to the .md
        # source, but the published page lives one directory deeper
        # (docs/a/b.md -> /a/b/), so compute the depth from the URL instead.
        depth = len(Path(path).parts)  # b.md in a/ -> ['a','b.md'] -> 2 levels up
        parts.append(
            '<div class="gk-reg-host" data-register="' + t["id"] + '" '
            'data-src="' + ("../" * depth) + 'assess/register-data.json">'
            '<p class="gk-muted">Loading the editable register…</p></div>\n'
        )

    parts.append("---\n")
    parts.append("## The template\n")

    if t.get("generate_body") == "checklist":
        parts.append(build_checklist_body(questions, by_id, path))
    else:
        parts.append(resolve_links(t["body"].rstrip(), path, by_id) + "\n")

    parts.append("---\n")
    parts.append("## Adaptation notes\n")
    for note in t["adaptation"]:
        body = resolve_links(note["note"].strip(), path, by_id)
        parts.append(f"- **{note['context']}:** {body}")
    parts.append("")

    related = [by_id[r] for r in t.get("related", []) if r in by_id]
    if related:
        parts.append("## Related\n")
        for r in related:
            parts.append(
                f"- [{r['title']}]({rel_link(path, r['path'])}) "
                f"— {status_pill(r['status'])}"
            )
        parts.append("")

    parts.append(snippets["not_legal_advice"])
    return "\n".join(parts)


def render_example_page(ex: dict, company: dict, by_id: dict) -> str:
    """A worked example: the same template, filled in for the fictional company."""
    path = ex["path"]
    tpl = by_id[ex["of"]]
    parts = [BANNER.format(source="examples.yml")]
    parts.append(f"# {ex['title']}\n")
    parts.append(
        f'!!! info "A worked example, not a template"\n'
        f"    This shows {company['name']} — a fictional company — using the\n"
        f"    [{tpl['title']}]({rel_link(path, tpl['path'])}). To start your own,\n"
        f"    use the blank template. Details here are illustrative.\n"
    )
    parts.append(resolve_links(ex["intro"].strip(), path, by_id) + "\n")
    parts.append("---\n")
    parts.append(resolve_links(ex["body"].rstrip(), path, by_id) + "\n")
    parts.append("---\n")
    parts.append("## What to take from this\n")
    for t_ in ex["takeaways"]:
        parts.append(f"- {resolve_links(' '.join(t_.split()), path, by_id)}")
    parts.append("")
    parts.append(
        f"[Use the blank {tpl['title']}]({rel_link(path, tpl['path'])})"
        "{ .md-button .md-button--primary }\n"
    )
    parts.append(SNIPPETS_CACHE["not_legal_advice"])
    return "\n".join(parts)


def render_examples_index(examples: list, company: dict, by_id: dict) -> str:
    path = "examples/index.md"
    parts = [BANNER.format(source="examples.yml")]
    parts.append("# Worked examples\n")
    parts.append(
        "Blank templates tell you what to fill in; they do not tell you what "
        "*good* looks like, or how much detail is expected. These are the same "
        "templates completed for one fictional company, so you can see the "
        "level of detail that makes an artefact defensible.\n"
    )
    parts.append(
        '!!! tip "Deliberately imperfect"\n'
        "    These examples include an amber board pack, a risk being tolerated,\n"
        "    a control that was failing in practice, and an outstanding action\n"
        "    past its owner. A worked example where everything is green teaches\n"
        "    nothing.\n"
    )
    parts.append(f"## {company['name']}\n")
    parts.append(company["profile"].rstrip() + "\n")
    parts.append("## The examples\n")
    parts.append("| Worked example | Illustrates |")
    parts.append("|---|---|")
    for ex in examples:
        tpl = by_id[ex["of"]]
        parts.append(
            f"| [{ex['title']}]({rel_link(path, ex['path'])}) "
            f"| [{tpl['title']}]({rel_link(path, tpl['path'])}) |"
        )
    parts.append("")
    parts.append(SNIPPETS_CACHE["not_legal_advice"])
    return "\n".join(parts)


def render_decide_page(decisions: list) -> str:
    """Mount point for the guided decisions and the decision log."""
    parts = [BANNER.format(source="decisions.yml")]
    parts.append("---\ntitle: Decide\nhide:\n  - toc\n---\n")
    parts.append("# Decide\n")
    parts.append(
        "The rest of this kit tells you what the options are. This page walks "
        "you to an answer — one question at a time, ending in a verdict with "
        "its reasoning recorded and dated.\n"
    )
    parts.append(
        '!!! tip "Why the record matters more than the answer"\n'
        "    The EU AI Act, ISO/IEC 42001 and NIST AI RMF all ask for\n"
        "    **documented, reasoned decisions**. A classification with no\n"
        "    rationale cannot be defended or sensibly reviewed later — so the\n"
        "    rationale trail is not paperwork, it is the deliverable.\n"
    )
    # Raw HTML attribute, so MkDocs does not rewrite it like a Markdown link.
    # decide.md publishes to /decide/, one level deep, hence the ../ prefix.
    parts.append(
        '<div id="gk-decide" data-src="../assess/decision-data.json">'
        '<p>Loading the guided decisions…</p></div>\n'
    )
    parts.append(SNIPPETS_CACHE["not_legal_advice"])
    return "\n".join(parts)


def render_scoring_page(bm: dict, questions: list, bands: list) -> str:
    """How the assessment scores, and — just as importantly — what it is not.

    The site tells people to evidence their controls. It would be indefensible
    to present a score without saying where the numbers come from, so this page
    states plainly that the thresholds are editorial rather than empirical.
    """
    path = "scoring.md"
    m = bm["method"]
    parts = [BANNER.format(source="benchmarks.yml")]
    parts.append("# How the scoring works\n")
    parts.append(
        f'<span class="gk-meta">Method v{m["version"]}</span> &nbsp;·&nbsp; '
        f'<span class="gk-meta">Last reviewed <strong>{m["reviewed"]}</strong></span>\n'
    )

    parts.append(
        '!!! warning "These thresholds are editorial judgement, not benchmarks"\n'
        "    They are **not** derived from a survey, a peer dataset, or any\n"
        "    published study, and they are not a certification standard.\n"
        "\n"
        "    This kit deliberately holds **no peer-comparison data**. Real\n"
        "    benchmarks would need a population of real assessments, which\n"
        "    would mean collecting your answers on a server — breaking the\n"
        "    guarantee that nothing leaves your browser. Inventing\n"
        "    plausible-looking peer percentages would be worse: a governance kit\n"
        "    that fabricates its own evidence base has no business telling you\n"
        "    to evidence your controls.\n"
    )

    parts.append("## What the score measures\n")
    parts.append(" ".join(m["summary"].split()) + "\n")
    parts.append("```\n" + " ".join(m["formula"].split()) + "\n```\n")

    parts.append("| | |")
    parts.append("|---|---|")
    parts.append(f"| **It is** | {' '.join(m['what_it_is'].split())} |")
    parts.append(f"| **It is not** | {' '.join(m['what_it_is_not'].split())} |")
    parts.append("")

    parts.append("## The bands, and why they sit there\n")
    parts.append("| Score | Band | Why this threshold |")
    parts.append("|---|---|---|")
    for b in bm["bands"]:
        rng = f"{b['min']}–100" if b["min"] == 90 else f"{b['min']}+"
        parts.append(
            f"| **{rng}** | {b['label']} | {' '.join(b['rationale'].split())} |"
        )
    parts.append("")

    parts.append("## What the weights mean\n")
    parts.append(
        "Every question carries a weight of 1–5 reflecting the consequence of "
        "its absence. This is why a missing inventory moves the score more than "
        "a missing metric.\n"
    )
    counts = Counter(q["weight"] for q in questions)
    parts.append("| Weight | Meaning | Questions |")
    parts.append("|---|---|---|")
    for w in bm["weights"]:
        parts.append(
            f"| **{w['value']} — {w['label']}** | {' '.join(w['meaning'].split())} "
            f"| {counts.get(w['value'], 0)} |"
        )
    parts.append("")
    parts.append(
        "The weights live in `data/questions.yml`. If you disagree with the "
        "emphasis for your sector, fork the repository and change them — that is "
        "what an open licence is for.\n"
    )

    parts.append("## Limitations you should know about\n")
    parts.append(
        "The report is meant to be presentable to a board, and a board should "
        "know what it is reading.\n"
    )
    for lim in bm["limitations"]:
        parts.append(f"**{lim['title']}.** {' '.join(lim['detail'].split())}\n")

    sc = bm["self_comparison"]
    parts.append(f"## {sc['title']}\n")
    parts.append(" ".join(sc["detail"].split()) + "\n")
    parts.append(f"**How often:** {' '.join(sc['cadence'].split())}\n")
    for g in sc["guidance"]:
        parts.append(f"- {' '.join(g.split())}")
    parts.append("")
    parts.append(
        '!!! tip "Snapshots are built in"\n'
        "    The [assessment](" + rel_link(path, "assess/index.md") + ") saves a\n"
        "    dated snapshot each time you ask it to, and the report shows your\n"
        "    movement between them. Snapshots stay in your browser like\n"
        "    everything else — export them if you want to keep them.\n"
    )
    parts.append(SNIPPETS_CACHE["not_legal_advice"])
    return "\n".join(parts)


def render_workspace_page(sheets_raw: dict, by_id: dict) -> str:
    """One page listing every editable register, for working across several."""
    path = "workspace.md"
    parts = [BANNER.format(source="spreadsheets.yml")]
    parts.append("# Workspace\n")
    parts.append(
        "Every register in the kit can be filled in directly in your browser — "
        "no download, no account, nothing uploaded. Your rows are saved on this "
        "device and can be exported to Excel or CSV at any time.\n"
    )
    parts.append(
        '!!! info "Where your data lives"\n'
        "    Each register is stored separately in this browser's local storage.\n"
        "    Clearing your browser data, or using a different device or a\n"
        "    private window, will lose it — so use **Save file** on anything you\n"
        "    want to keep, and **Open file** to pick it back up later.\n"
    )
    parts.append("## The editable registers\n")
    parts.append("| Register | What it records | Columns |")
    parts.append("|---|---|---|")
    for tid, spec in sheets_raw.items():
        t = by_id[tid]
        n = len(spec["columns"]) + sum(
            len(s["columns"]) for s in spec.get("extra_sheets", []))
        purpose = " ".join(t["purpose"].split())
        if len(purpose) > 120:
            purpose = purpose[:117].rsplit(" ", 1)[0] + "…"
        parts.append(
            f"| [{t['title']}]({rel_link(path, t['path'])}) | {purpose} | {n} |"
        )
    parts.append("")
    parts.append(
        SNIPPET_ASSESS.format(assess=rel_link(path, "assess/index.md"))
    )
    parts.append("## How it fits together\n")
    parts.append(
        "1. **[Take the assessment](" + rel_link(path, "assess/index.md") +
        ")** to find your gaps.\n"
        "2. Open the **Risk Register** — it offers to turn every open gap into a "
        "draft risk, already scored, so you are editing rather than starting "
        "from a blank page.\n"
        "3. Fill in the **AI System Inventory** as you discover systems; it is "
        "the register everything else depends on.\n"
        "4. Export to Excel when you need to share, or print the report for a "
        "board pack.\n"
    )
    parts.append(SNIPPETS_CACHE["not_legal_advice"])
    return "\n".join(parts)


def render_tasks_page(tasks: list, by_id: dict) -> str:
    """The "I've been asked to…" index.

    Most people arrive with a request from someone else, not a browsing intent.
    This maps the ask, in the words it usually arrives in, to a starting order.
    """
    path = "tasks.md"
    parts = [BANNER.format(source="tasks.yml")]
    parts.append("# I've been asked to…\n")
    parts.append(
        "Most people land here because someone asked them for something. Find "
        "the request below and start where it points.\n"
    )
    parts.append(
        SNIPPET_ASSESS.format(assess=rel_link(path, "assess/index.md"))
    )
    for t in tasks:
        parts.append(f'## "{t["ask"]}"\n')
        parts.append(
            f"**Usually asked by:** {t['who']}  \n"
            f"**Rough effort:** {t['effort']}\n"
        )
        parts.append("**Start here, in this order:**\n")
        for n, tid in enumerate(t["start"], start=1):
            tpl = by_id.get(tid)
            if tpl is None:
                raise SystemExit(
                    f"ERROR: task {t['ask']!r} references unknown template '{tid}'"
                )
            parts.append(
                f"{n}. [{tpl['title']}]({rel_link(path, tpl['path'])})"
                f" — {' '.join(tpl['purpose'].split())[:110].rsplit(' ', 1)[0]}…"
            )
        parts.append("")
        parts.append(
            f'!!! tip "Before you start"\n'
            f"    {' '.join(t['note'].split())}\n"
        )
    parts.append(SNIPPETS_CACHE["not_legal_advice"])
    return "\n".join(parts)


def render_plans_page(plans: list, by_id: dict) -> str:
    """30/60/90-day plans, one per starting path, plus a small-org variant."""
    path = "plans.md"
    parts = [BANNER.format(source="plans.yml")]
    parts.append("# 30/60/90-day plans\n")
    parts.append(
        "Knowing which templates you need is not the same as knowing what order "
        "to do them in. These are sequenced plans with rough effort, so you can "
        "plan resource and tell a sponsor when things will land.\n"
    )
    parts.append(
        '!!! note "Effort is for one person, not full time"\n'
        "    Estimates are person-days for whoever is running this, assuming it\n"
        "    is not their only job. They cover a competent first pass — not a\n"
        "    polished, audited version.\n"
    )
    parts.append("## Pick your path\n")
    parts.append("| Path | When it fits | Total effort |")
    parts.append("|---|---|---|")
    for p in plans:
        anchor = p["name"].lower().replace(" ", "-").replace("/", "").replace(",", "")
        parts.append(
            f"| [{p['name']}](#{anchor}) | {' '.join(p['when'].split())} "
            f"| {p['total']} |"
        )
    parts.append("")

    for p in plans:
        parts.append(f"## {p['name']}\n")
        if p.get("small_org"):
            parts.append(
                '!!! tip "This is not a cut-down version"\n'
                "    The rest of the kit assumes a committee and named specialist\n"
                "    roles. This path deliberately does not — it is a different\n"
                "    sequence for organisations that have neither.\n"
            )
        parts.append(f"**When it fits:** {' '.join(p['when'].split())}  ")
        parts.append(f"**Assumes:** {' '.join(p['assumes'].split())}  ")
        parts.append(f"**Total effort:** {p['total']}\n")

        for ph in p["phases"]:
            parts.append(f"### {ph['window']} — {ph['goal']}\n")
            parts.append(f"*Effort: {ph['effort']}*\n")
            for n, s in enumerate(ph["steps"], start=1):
                tpl = by_id.get(s["template"])
                if tpl is None:
                    raise SystemExit(
                        f"ERROR: plan '{p['id']}' references unknown template "
                        f"'{s['template']}'"
                    )
                parts.append(
                    f"{n}. **{s['do']}** — [{tpl['title']}]"
                    f"({rel_link(path, tpl['path'])}) · *{s['effort']}*"
                )
                if s.get("note"):
                    parts.append(f"   <br>{' '.join(s['note'].split())}")
            parts.append("")
            parts.append("**You are done when:**\n")
            for d in ph["done"]:
                parts.append(f"- [ ] {d}")
            parts.append("")
        parts.append("---\n")

    parts.append(SNIPPETS_CACHE["not_legal_advice"])
    return "\n".join(parts)


def render_crosswalk_page(cw: dict, by_id: dict) -> str:
    """Map the kit's templates onto ISO 42001, NIST AI RMF, Singapore, EU AI Act."""
    path = "crosswalk.md"
    frameworks = cw["frameworks"]
    parts = [BANNER.format(source="crosswalk.yml")]
    parts.append("# Standards crosswalk\n")
    parts.append(
        "The same control usually satisfies several frameworks at once. This "
        "maps the kit onto the major AI governance regimes, so you can build a "
        "control once and justify it against whichever standard you are held "
        "to — or wanted to cite when asking for budget.\n"
    )
    parts.append(
        '!!! warning "Indicative, not certified equivalence"\n'
        "    These mappings help you navigate. They are **not** certified\n"
        "    equivalences, and clause numbering changes between editions.\n"
        "    Verify against the standard itself before relying on a mapping in\n"
        "    an audit or certification context.\n"
    )

    parts.append("## The frameworks\n")
    for f in frameworks:
        parts.append(f"### [{f['name']}]({f['url']})\n")
        parts.append(f"*{f['full']}*\n")
        parts.append(" ".join(f["short"].split()) + "\n")
        parts.append(f"**Best for:** {' '.join(f['audience'].split())}  ")
        parts.append(f"**Worth knowing:** {' '.join(f['note'].split())}\n")

    parts.append("## The crosswalk\n")
    parts.append(
        "Read a row across to see how each regime expresses the same "
        "obligation, then use the templates in the last column to satisfy all "
        "of them at once.\n"
    )

    head = "| Theme | " + " | ".join(f["name"] for f in frameworks) + " | Templates |"
    parts.append(head)
    parts.append("|" + "---|" * (len(frameworks) + 2))
    for row in cw["rows"]:
        cells = [f"**{row['theme']}**"]
        for f in frameworks:
            cells.append(row.get(f["id"], "—"))
        links = []
        for tid in row["templates"]:
            tpl = by_id.get(tid)
            if tpl is None:
                raise SystemExit(
                    f"ERROR: crosswalk row '{row['theme']}' references unknown "
                    f"template '{tid}'"
                )
            links.append(f"[{tpl['title']}]({rel_link(path, tpl['path'])})")
        cells.append(" · ".join(links))
        parts.append("| " + " | ".join(cells) + " |")
    parts.append("")

    parts.append("## Using this in practice\n")
    parts.append(
        "- **Certifying to ISO/IEC 42001?** The crosswalk shows which templates "
        "produce the documented information each clause expects. You will still "
        "need a management system around them.\n"
        "- **Using NIST AI RMF as your vocabulary?** The functions map cleanly "
        "onto the kit's structure: Govern to the operating model, Map to the "
        "registers, Measure to risk and control, Manage to monitoring and "
        "reporting.\n"
        "- **Operating in several jurisdictions?** Build to the strictest "
        "applicable requirement per theme, then map outwards. Maintaining "
        "parallel control sets per regime is how governance programmes collapse "
        "under their own weight.\n"
    )
    parts.append(SNIPPETS_CACHE["not_legal_advice"])
    return "\n".join(parts)


def render_markdown_download(t: dict, by_id: dict, questions: list) -> str:
    """The template as standalone Markdown, for pasting into a wiki.

    Cross-references become plain template names rather than relative links,
    since those links would be broken once the file leaves the site.
    """
    def plain(text):
        return re.sub(
            r"\{\{([a-z0-9\-]+)\}\}",
            lambda m: by_id[m.group(1)]["title"] if m.group(1) in by_id else m.group(1),
            text or "",
        )

    out = [f"# {t['title']}\n"]
    out.append(f"**Purpose.** {plain(' '.join(t['purpose'].split()))}\n")
    out.append(f"**When to use it.** {plain(' '.join(t['when_to_use'].split()))}\n")
    out.append(f"**How to use it.** {plain(' '.join(t['how_to_use'].split()))}\n")
    out.append("---\n")

    if t.get("generate_body") == "checklist":
        items = sorted([q for q in questions if q.get("checklist")],
                       key=lambda q: q["checklist"])
        current = None
        for q in items:
            if q["category"] != current:
                current = q["category"]
                out.append(f"\n## {current}\n")
            out.append(f"- [ ] **{q['checklist']}.** {q['text']}")
            out.append(f"      *{' '.join(q['help'].split())}*")
            if q.get("evidence"):
                out.append(f"      **Evidence:** {' '.join(q['evidence'].split())}")
            out.append("")
        out.append("")
    else:
        # Admonitions are MkDocs-specific; flatten them to blockquotes so the
        # file renders sensibly in GitHub, Notion, Confluence, and plain editors.
        body = plain(t["body"].rstrip())
        lines, flat = body.split("\n"), []
        i = 0
        while i < len(lines):
            m = re.match(r'^!!!\s+\w+\s*"?([^"]*)"?\s*$', lines[i].strip())
            if m:
                flat.append(f"> **{m.group(1).strip() or 'Note'}**")
                i += 1
                while i < len(lines) and (not lines[i].strip()
                                          or lines[i].startswith("    ")):
                    if lines[i].strip():
                        flat.append("> " + lines[i].strip())
                    i += 1
                flat.append("")
                continue
            flat.append(lines[i])
            i += 1
        out.append("\n".join(flat) + "\n")

    out.append("---\n")
    out.append("## Adaptation notes\n")
    for note in t["adaptation"]:
        out.append(f"- **{note['context']}:** {plain(' '.join(note['note'].split()))}")
    out.append("")
    out.append("---\n")
    out.append(
        "*From the [Open Data & AI Governance Kit]"
        "(https://lsdeva.github.io/governance-kit/). Licensed "
        "[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) — free to use, "
        "adapt, and share with attribution.*\n"
    )
    out.append(
        "***Not legal advice.** Adapt to your jurisdiction, sector, and risk "
        "appetite, and have qualified counsel review anything material.*\n"
    )
    return "\n".join(out)


def render_section_index(section: dict, templates: list, by_id: dict) -> str:
    path = f"{section['id']}/index.md"
    parts = [BANNER.format(source="sections.yml + templates.yml")]
    parts.append(f"# {section['title']}\n")
    parts.append(section["blurb"].strip() + "\n")
    parts.append("| Template | Status | Purpose |")
    parts.append("|---|---|---|")
    for t in templates:
        purpose = " ".join(t["purpose"].split())
        if len(purpose) > 155:
            purpose = purpose[:152].rsplit(" ", 1)[0] + "…"
        parts.append(
            f"| [{t['title']}]({rel_link(path, t['path'])}) "
            f"| {status_pill(t['status'])} | {purpose} |"
        )
    parts.append("")
    parts.append(
        SNIPPET_ASSESS.format(assess=rel_link(path, "assess/index.md"))
    )
    return "\n".join(parts)


SNIPPET_ASSESS = ""  # filled from snippets.yml at runtime
SNIPPETS_CACHE = {}  # ditto; used by the example renderers
EXAMPLE_OF = {}      # template id -> worked example, for the "see it filled in" link
BANDS_RUNTIME = []   # built from data/benchmarks.yml in main()
DEFAULTS = {}        # id -> recommended default, from data/defaults.yml


def build_assessment_json(roles, questions, templates, sections) -> dict:
    """The single JSON payload the /assess/ app fetches.

    Template links are pre-resolved to paths relative to docs/assess/ so the
    browser never has to know the site structure.
    """
    by_id = {t["id"]: t for t in templates}

    tpl_out = {}
    for t in templates:
        tpl_out[t["id"]] = {
            "id": t["id"],
            "title": t["title"],
            "section": t["section"],
            "status": t["status"],
            "url": rel_link("assess/index.md", t["path"]).replace(".md", "/"),
            "purpose": " ".join(t["purpose"].split()),
        }

    q_out = []
    for q in questions:
        missing = [t for t in q.get("templates", []) if t not in by_id]
        if missing:
            raise SystemExit(f"ERROR: {q['id']} references unknown template(s): {missing}")
        q_out.append(
            {
                "id": q["id"],
                "text": q["text"],
                "help": " ".join(q["help"].split()),
                "evidence": " ".join((q.get("evidence") or "").split()),
                "category": q["category"],
                "roles": q["applies_to"],
                "weight": q["weight"],
                "templates": q.get("templates", []),
                "obligation": q.get("obligation", {}),
                "checklist": q.get("checklist"),
            }
        )

    role_ids = {r["id"] for r in roles}
    for q in questions:
        unknown = [r for r in q["applies_to"] if r not in role_ids]
        if unknown:
            raise SystemExit(f"ERROR: {q['id']} references unknown role(s): {unknown}")

    return {
        "version": 1,
        "roles": [
            {
                "id": r["id"],
                "name": r["name"],
                "short": " ".join(r["short"].split()),
                "focus": r.get("focus", []),
                "questionCount": sum(1 for q in questions if r["id"] in q["applies_to"]),
            }
            for r in roles
        ],
        "questions": q_out,
        "templates": tpl_out,
        "categories": CATEGORY_ORDER,
        "bands": BANDS_RUNTIME,
        "sections": {s["id"]: s["title"] for s in sections},
    }


def build_nav(sections, templates, examples, tasks, plans, crosswalk, workspace, decisions) -> str:
    lines = [NAV_START, "nav:", "  - Home: index.md", "  - Get started: getting-started.md",
             "  - Assessment: assess/index.md"]
    if workspace:
        lines.append("  - Workspace: workspace.md")
    if decisions:
        lines.append("  - Decide: decide.md")
    lines.append("  - How scoring works: scoring.md")
    if tasks:
        lines.append("  - I've been asked to…: tasks.md")
    if plans:
        lines.append("  - 30/60/90-day plans: plans.md")
    if crosswalk:
        lines.append("  - Standards crosswalk: crosswalk.md")
    for s in sections:
        lines.append(f"  - {s['nav']}:")
        lines.append(f"      - Overview: {s['id']}/index.md")
        for t in templates:
            if t["section"] == s["id"]:
                lines.append(f"      - {t.get('nav', t['title'])}: {t['path']}")
    if examples:
        lines.append("  - Worked examples:")
        lines.append("      - Overview: examples/index.md")
        for e in examples:
            lines.append(f"      - {e.get('nav', e['title'])}: {e['path']}")
    lines.append("  - Contributing: contributing.md")
    lines.append("  - About: about.md")
    lines.append(NAV_END)
    return "\n".join(lines)


def write(path: Path, content: str, written: list, check: bool) -> None:
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == content:
        return
    if check:
        written.append(path)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    written.append(path)


def main() -> int:
    global SNIPPET_ASSESS

    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report stale files without writing; exit 1 if any")
    args = ap.parse_args()

    sections = load("sections.yml")
    roles = load("roles.yml")
    questions = load("questions.yml")
    templates = load("templates.yml")
    snippets = load("snippets.yml")

    SNIPPET_ASSESS = snippets["assess_callout"]
    SNIPPETS_CACHE.update(snippets)
    sheets_raw = load("spreadsheets.yml") or {}
    SPREADSHEET_IDS.update(sheets_raw.keys())

    defaults_list = load("defaults.yml") or []
    dup = [i for i, c in Counter(d["id"] for d in defaults_list).items() if c > 1]
    if dup:
        raise SystemExit(f"ERROR: duplicate default ids: {dup}")
    for d in defaults_list:
        for field in ("label", "value", "unless", "why"):
            if not str(d.get(field, "")).strip():
                raise SystemExit(
                    f"ERROR: default '{d['id']}' is missing `{field}`. Every "
                    "default needs a value, a deviation condition, and the "
                    "reasoning — otherwise it is just another unexplained number."
                )
    DEFAULTS.update({d["id"]: d for d in defaults_list})

    benchmarks = load("benchmarks.yml")
    bands = sorted(benchmarks["bands"], key=lambda b: -b["min"])
    if bands[-1]["min"] != 0:
        raise SystemExit("ERROR: benchmarks.yml bands must include a 0 floor")
    for b in bands:
        if b["label"] not in BAND_BLURBS:
            raise SystemExit(
                f"ERROR: band '{b['label']}' has no blurb in BAND_BLURBS"
            )
    BANDS_RUNTIME[:] = [
        {"min": b["min"], "label": b["label"], "blurb": BAND_BLURBS[b["label"]]}
        for b in bands
    ]

    examples_data = load("examples.yml") or {}
    company = examples_data.get("company", {})
    examples = examples_data.get("examples", [])
    EXAMPLE_OF.update({e["of"]: e for e in examples})

    by_id = {t["id"]: t for t in templates}

    # ---- integrity checks: fail loudly rather than generating a broken site --
    dupes = [i for i, c in Counter(t["id"] for t in templates).items() if c > 1]
    if dupes:
        raise SystemExit(f"ERROR: duplicate template ids: {dupes}")

    section_ids = {s["id"] for s in sections}
    for t in templates:
        if t["section"] not in section_ids:
            raise SystemExit(f"ERROR: {t['id']} has unknown section '{t['section']}'")
        if t["status"] not in STATUS_LABELS:
            raise SystemExit(f"ERROR: {t['id']} has unknown status '{t['status']}'")
        for r in t.get("related", []):
            if r not in by_id:
                raise SystemExit(f"ERROR: {t['id']} relates to unknown template '{r}'")

    qdupes = [i for i, c in Counter(q["id"] for q in questions).items() if c > 1]
    if qdupes:
        raise SystemExit(f"ERROR: duplicate question ids: {qdupes}")
    for q in questions:
        if q["category"] not in CATEGORY_ORDER:
            raise SystemExit(f"ERROR: {q['id']} has unknown category '{q['category']}'")
        if not 1 <= q["weight"] <= 5:
            raise SystemExit(f"ERROR: {q['id']} weight {q['weight']} outside 1-5")
        if not q["applies_to"]:
            raise SystemExit(f"ERROR: {q['id']} applies to no roles")
        if not q.get("evidence"):
            raise SystemExit(
                f"ERROR: {q['id']} has no `evidence:`. Every question must say "
                "what would satisfy an auditor, or the exported report cannot "
                "double as an evidence list."
            )

    cl = [q["checklist"] for q in questions if q.get("checklist")]
    if sorted(cl) != list(range(1, len(cl) + 1)):
        raise SystemExit(f"ERROR: checklist numbers must be 1..N with no gaps; got {sorted(cl)}")

    for r in roles:
        n = sum(1 for q in questions if r["id"] in q["applies_to"])
        if n < 5:
            raise SystemExit(f"ERROR: role '{r['id']}' has only {n} questions (minimum 5)")

    for e in examples:
        if e["of"] not in by_id:
            raise SystemExit(f"ERROR: example '{e['id']}' illustrates unknown template '{e['of']}'")
    ex_dupes = [i for i, c in Counter(e["of"] for e in examples).items() if c > 1]
    if ex_dupes:
        raise SystemExit(f"ERROR: more than one example for template(s): {ex_dupes}")

    written: list[Path] = []

    # ---- template pages -----------------------------------------------------
    for t in templates:
        write(DOCS / t["path"],
              render_template_page(t, by_id, snippets, questions), written, args.check)
        # Raw Markdown download: the template on its own, without site chrome or
        # cross-page links, ready to paste into a wiki or an internal doc.
        #
        # Written with a .md.txt extension because MkDocs treats any .md file
        # under docs/ as a page to render — a plain .md here would be served as
        # HTML, so the "Markdown" button would hand back the wrong thing.
        write(DOCS / "downloads" / (t["id"] + ".md.txt"),
              render_markdown_download(t, by_id, questions), written, args.check)

    # ---- section index pages ------------------------------------------------
    for s in sections:
        in_section = [t for t in templates if t["section"] == s["id"]]
        write(DOCS / s["id"] / "index.md",
              render_section_index(s, in_section, by_id), written, args.check)

    # ---- generated stats snippet -------------------------------------------
    # Counts injected into hand-written pages, so a claim like "25 of 26 fully
    # drafted" cannot drift from what the data actually says.
    # Written to the repo root, not docs/, because any .md under docs/ becomes
    # a page. pymdownx.snippets pulls it into the landing page.
    n_ready = sum(1 for t in templates if t["status"] == "ready")
    stats = (
        f"{len(templates)} templates · **{n_ready} of {len(templates)} fully "
        f"drafted** · {len(questions)} assessment questions across "
        f"{len(roles)} roles · {len(examples)} worked examples\n"
    )
    write(ROOT / "snippets" / "stats.md", stats, written, args.check)

    # ---- guided decisions ---------------------------------------------------
    decisions = load("decisions.yml") or []
    if decisions:
        # Validate the tree: every branch must terminate in a real outcome or a
        # real question, or a user hits a dead end mid-decision.
        for d in decisions:
            qids = {q["id"] for q in d["questions"]}
            oids = {o["id"] for o in d["outcomes"]}
            if d["start"] not in qids:
                raise SystemExit(
                    f"ERROR: decision '{d['id']}' starts at unknown question "
                    f"'{d['start']}'")
            for q in d["questions"]:
                targets = []
                if q.get("options"):
                    targets = [o["next"] for o in q["options"]]
                else:
                    targets = [q.get(True), q.get(False)]
                for tgt in targets:
                    if tgt is None:
                        raise SystemExit(
                            f"ERROR: {d['id']}/{q['id']} has a branch with no "
                            "destination")
                    if isinstance(tgt, str):
                        if tgt not in qids:
                            raise SystemExit(
                                f"ERROR: {d['id']}/{q['id']} points at unknown "
                                f"question '{tgt}'")
                    elif tgt.get("outcome") not in oids:
                        raise SystemExit(
                            f"ERROR: {d['id']}/{q['id']} points at unknown "
                            f"outcome '{tgt.get('outcome')}'")
            for o in d["outcomes"]:
                for tid in o.get("templates", []):
                    if tid not in by_id:
                        raise SystemExit(
                            f"ERROR: outcome '{o['id']}' references unknown "
                            f"template '{tid}'")
                # An unquoted "Label: text" list item parses as a dict, not a
                # string, and reaches the browser as an object the renderer
                # cannot append. Catch it here rather than at runtime.
                for field in ("actions",):
                    for item in o.get(field, []):
                        if not isinstance(item, str):
                            raise SystemExit(
                                f"ERROR: outcome '{o['id']}' has a non-string "
                                f"{field} entry ({item!r}). A YAML list item "
                                "containing a colon must be quoted or written "
                                "as a folded block."
                            )
                for field in ("headline", "detail", "tier", "severity"):
                    if not isinstance(o.get(field), str):
                        raise SystemExit(
                            f"ERROR: outcome '{o['id']}' field '{field}' must "
                            f"be a string, got {type(o.get(field)).__name__}")

            # Walk every path exhaustively: no unreachable question, no cycle,
            # no outcome that can never be reached, and every branch terminates.
            qmap = {q["id"]: q for q in d["questions"]}
            reached_q, reached_o = set(), set()

            def walk(qid, depth):
                if depth > 40:
                    raise SystemExit(
                        f"ERROR: decision '{d['id']}' has a cycle at '{qid}'")
                reached_q.add(qid)
                q = qmap[qid]
                if q.get("options"):
                    nxt = [o["next"] for o in q["options"]]
                else:
                    nxt = [q.get(True), q.get(False)]
                for tgt in nxt:
                    if isinstance(tgt, str):
                        walk(tgt, depth + 1)
                    else:
                        reached_o.add(tgt["outcome"])

            walk(d["start"], 0)
            orphan_q = qids - reached_q
            if orphan_q:
                raise SystemExit(
                    f"ERROR: decision '{d['id']}' has unreachable question(s): "
                    f"{sorted(orphan_q)}")
            orphan_o = oids - reached_o
            if orphan_o:
                raise SystemExit(
                    f"ERROR: decision '{d['id']}' has outcome(s) no path "
                    f"reaches: {sorted(orphan_o)}")

        # PyYAML parses bare yes/no keys as booleans; the app expects "yes"/"no".
        def norm(q):
            out = dict(q)
            if True in out:
                out["yes"] = out.pop(True)
            if False in out:
                out["no"] = out.pop(False)
            return out

        payload = {
            "version": 1,
            "decisions": [
                {
                    "id": d["id"],
                    "title": d["title"],
                    "short": " ".join(d["short"].split()),
                    "why": " ".join(d["why"].split()),
                    "intro": " ".join(d["intro"].split()),
                    "start": d["start"],
                    "questions": [norm(q) for q in d["questions"]],
                    "outcomes": d["outcomes"],
                }
                for d in decisions
            ],
            "templates": {
                t["id"]: {
                    "id": t["id"],
                    "title": t["title"],
                    "url": rel_link("assess/index.md", t["path"]).replace(".md", "/"),
                }
                for t in templates
            },
        }
        write(DOCS / "assess" / "decision-data.json",
              json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
              written, args.check)
        write(DOCS / "decide.md", render_decide_page(decisions), written, args.check)

    # ---- scoring method -----------------------------------------------------
    write(DOCS / "scoring.md",
          render_scoring_page(benchmarks, questions, BANDS_RUNTIME),
          written, args.check)

    # ---- workspace ----------------------------------------------------------
    if sheets_raw:
        write(DOCS / "workspace.md",
              render_workspace_page(sheets_raw, by_id), written, args.check)

    # ---- task index, plans, crosswalk ---------------------------------------
    tasks = load("tasks.yml") or []
    if tasks:
        write(DOCS / "tasks.md", render_tasks_page(tasks, by_id), written, args.check)

    plans = load("plans.yml") or []
    if plans:
        write(DOCS / "plans.md", render_plans_page(plans, by_id), written, args.check)

    crosswalk = load("crosswalk.yml") or {}
    if crosswalk:
        write(DOCS / "crosswalk.md",
              render_crosswalk_page(crosswalk, by_id), written, args.check)

    # ---- worked examples ----------------------------------------------------
    if examples:
        write(DOCS / "examples" / "index.md",
              render_examples_index(examples, company, by_id), written, args.check)
        for e in examples:
            write(DOCS / e["path"],
                  render_example_page(e, company, by_id), written, args.check)

    # ---- editable register data --------------------------------------------
    # Same source as the .xlsx downloads, so the in-browser editor and the
    # generated spreadsheet can never disagree about columns or dropdowns.
    # sheets_raw is loaded near the top, alongside the other data files.
    registers = {}
    for tid, spec in sheets_raw.items():
        tpl = by_id[tid]
        registers[tid] = {
            "id": tid,
            "title": tpl["title"],
            "url": rel_link("assess/index.md", tpl["path"]).replace(".md", "/"),
            "main": {
                "name": spec.get("sheet", tpl["title"]),
                "intro": " ".join(spec.get("intro", "").split()),
                "columns": spec["columns"],
                "rows": spec.get("rows", []),
            },
            "extra_sheets": [
                {
                    "name": s["name"],
                    "columns": s["columns"],
                    "rows": s.get("rows", []),
                }
                for s in spec.get("extra_sheets", [])
            ],
        }
    write(DOCS / "assess" / "register-data.json",
          json.dumps({"version": 1, "registers": registers},
                     indent=2, ensure_ascii=False) + "\n",
          written, args.check)

    # ---- assessment data ----------------------------------------------------
    payload = build_assessment_json(roles, questions, templates, sections)
    write(DOCS / "assess" / "assessment-data.json",
          json.dumps(payload, indent=2, ensure_ascii=False) + "\n", written, args.check)

    # ---- navigation in mkdocs.yml ------------------------------------------
    mk = ROOT / "mkdocs.yml"
    text = mk.read_text(encoding="utf-8")
    nav = build_nav(sections, templates, examples, tasks, plans, crosswalk, bool(sheets_raw), decisions)
    if NAV_START in text and NAV_END in text:
        new_text = re.sub(
            re.escape(NAV_START) + r".*?" + re.escape(NAV_END),
            nav.replace("\\", "\\\\"),
            text,
            flags=re.S,
        )
    else:
        new_text = re.sub(r"\nnav:\n(?:.*\n)*?\Z", "\n" + nav + "\n", text)
    if new_text != text:
        if not args.check:
            mk.write_text(new_text, encoding="utf-8", newline="\n")
        written.append(mk)

    # ---- verify raw-HTML data-src attributes resolve ------------------------
    # MkDocs rewrites Markdown links but NOT raw HTML attributes, so a data-src
    # that looks right relative to the .md source can 404 on the published page
    # (docs/a/b.md publishes to /a/b/, one level deeper). This has caused two
    # silent breakages; check it at build time instead of in a browser.
    for md in DOCS.rglob("*.md"):
        text = md.read_text(encoding="utf-8")
        for m in re.finditer(r'data-src="([^"]+)"', text):
            src = m.group(1)
            if src.startswith(("http://", "https://", "/")):
                continue
            # Work out the published URL directory for this page:
            #   docs/a/b.md      -> /a/b/     (assets resolve from /a/b/)
            #   docs/a/index.md  -> /a/       (assets resolve from /a/)
            rel = md.relative_to(DOCS)
            if md.name == "index.md":
                url_dir = rel.parent
            else:
                url_dir = rel.parent / rel.stem

            # Resolve src against that directory the way a browser would.
            # Done with plain string segments, not Path.resolve(), which on
            # Windows would drag in the drive root and collapse the ".." wrongly.
            segs = [s for s in url_dir.as_posix().split("/") if s and s != "."]
            for part in src.split("/"):
                if part in ("", "."):
                    continue
                if part == "..":
                    if not segs:
                        raise SystemExit(
                            f"ERROR: {rel} data-src=\"{src}\" escapes the site root"
                        )
                    segs.pop()
                else:
                    segs.append(part)
            target = "/".join(segs)
            wanted = DOCS / target
            if not wanted.exists():
                raise SystemExit(
                    f"ERROR: {rel} has data-src=\"{src}\", which resolves to "
                    f"{target} from the published page /"
                    f"{url_dir.as_posix()}/ — no such file. MkDocs does not "
                    "rewrite raw HTML attributes the way it rewrites Markdown "
                    "links, so this would 404 in the browser."
                )

    # ---- report -------------------------------------------------------------
    if args.check:
        if written:
            print("STALE — these files differ from the data files:")
            for p in written:
                print(f"  {p.relative_to(ROOT)}")
            print("\nRun: python tools/build_content.py")
            return 1
        print(f"Up to date: {len(templates)} templates, {len(questions)} questions, "
              f"{len(roles)} roles.")
        return 0

    print(f"Generated {len(templates)} template pages, {len(sections)} section indexes, "
          f"assessment data ({len(questions)} questions, {len(roles)} roles).")
    if written:
        print(f"Changed {len(written)} file(s).")
    else:
        print("No changes — already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
