#!/usr/bin/env python3
"""Generate the site's Markdown pages and the assessment data from data/*.yml.

The data files under data/ are the single source of truth. This script renders:

  * one page per template            -> docs/<section>/<page>.md
  * one index page per section       -> docs/<section>/index.md
  * the EU AI Act readiness checklist -> generated from questions.yml
  * the assessment app's data        -> docs/assess/assessment-data.json
  * the navigation block             -> mkdocs.yml (between NAV markers)

Every generated file carries a "do not edit" header. CI re-runs this script and
fails if the working tree changed, so a hand-edit of a generated page is caught
loudly instead of being silently overwritten on the next build.

Usage:
    python tools/build_content.py            # write files
    python tools/build_content.py --check    # verify only; non-zero if stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DOCS = ROOT / "docs"

BANNER = (
    "<!-- GENERATED FILE — DO NOT EDIT.\n"
    "     Source: data/{source}\n"
    "     Regenerate with: python tools/build_content.py -->\n\n"
)

NAV_START = "# NAV:START (generated by tools/build_content.py - do not edit by hand)"
NAV_END = "# NAV:END"

STATUS_LABELS = {"ready": "Ready", "draft": "Draft", "stub": "Stub"}

# Template ids that also get an .xlsx. Populated from data/spreadsheets.yml at
# runtime so the download buttons cannot advertise a file that is not built.
SPREADSHEET_IDS = set()

# Order categories appear in the questionnaire and the report.
CATEGORY_ORDER = [
    "Inventory",
    "Risk",
    "Documentation",
    "Oversight",
    "Transparency",
    "Third-party",
    "Literacy",
]

# Readiness bands, shared by the report and the checklist page.
BANDS = [
    {"min": 90, "label": "Advanced", "blurb": "Controls are measured and independently assured. Focus on continuous improvement."},
    {"min": 70, "label": "Established", "blurb": "The core is in place and operating. Focus on evidencing that controls work."},
    {"min": 40, "label": "Developing", "blurb": "Foundations exist but coverage is uneven. Close the documentation and process gaps."},
    {"min": 0, "label": "Early", "blurb": "Significant exposure. Start with inventory, prohibited-practice screening, and accountability."},
]


def load(name: str):
    with open(DATA / name, encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def rel_link(from_path: str, to_path: str) -> str:
    """Relative link from one docs page to another, MkDocs-style."""
    from_dir = Path(from_path).parent
    return Path(__import__("os").path.relpath(Path(to_path), from_dir)).as_posix()


def resolve_links(text: str, from_path: str, by_id: dict) -> str:
    """Replace {{template-id}} with a proper relative Markdown link.

    Keeping cross-references as ids means a page can be moved by changing its
    `path` in the data file without producing a single broken link.
    """
    if not text:
        return text

    def sub(match: re.Match) -> str:
        tid = match.group(1).strip()
        target = by_id.get(tid)
        if target is None:
            raise SystemExit(
                f"ERROR: unknown template id '{{{{{tid}}}}}' referenced from {from_path}"
            )
        return f"[{target['title']}]({rel_link(from_path, target['path'])})"

    return re.sub(r"\{\{([a-z0-9\-]+)\}\}", sub, text)


def status_pill(status: str) -> str:
    return f'<span class="pill {status}">{STATUS_LABELS[status]}</span>'


def build_checklist_body(questions: list, templates_by_id: dict, page_path: str) -> str:
    """Render the 25-point checklist FROM the question bank.

    This is why the published checklist and the assessment tool cannot drift:
    both read the same list.
    """
    items = sorted(
        [q for q in questions if q.get("checklist")], key=lambda q: q["checklist"]
    )
    groups: dict[str, list] = {}
    for q in items:
        groups.setdefault(q["category"], []).append(q)

    out = [
        "This checklist is generated from the same question bank as the "
        "[interactive assessment](" + rel_link(page_path, "assess/index.md") + "), "
        "so the two can never disagree.\n",
        "**Tick the boxes as you go** — your progress is saved in this browser "
        "and nothing is uploaded.\n",
        # docs/assess/checklist.js finds this element, enables the checkboxes,
        # and renders the live count and clear control into it.
        '<div id="gk-checklist" class="gk-cl"></div>\n',
    ]

    for category in CATEGORY_ORDER:
        if category not in groups:
            continue
        out.append(f"### {category}\n")
        for q in groups[category]:
            n = q["checklist"]
            out.append(f"- [ ] **{n}.** {q['text']}")
            out.append(f"    <br><small>{q['help'].strip()}</small>")
            if q.get("evidence"):
                out.append(
                    "    <br><small class=\"gk-ev\">**Evidence:** "
                    + " ".join(q["evidence"].split()) + "</small>"
                )
            tpl = [templates_by_id[t] for t in q.get("templates", []) if t in templates_by_id]
            if tpl:
                links = " · ".join(
                    f"[{t['title']}]({rel_link(page_path, t['path'])})" for t in tpl[:3]
                )
                out.append(f"    <br><small>**Fix with:** {links}</small>")
            out.append("")

    out.append("---\n")
    out.append("### Turn gaps into action\n")
    out.append(
        "Every unticked item maps to something in this kit. For a scored, "
        "role-specific version of this checklist — with a report you can present "
        "to a board or a regulator — take the "
        f"[interactive assessment]({rel_link(page_path, 'assess/index.md')}). "
        "Your answers stay in your browser.\n"
    )
    return "\n".join(out)


def render_template_page(t: dict, by_id: dict, snippets: dict, questions: list) -> str:
    path = t["path"]
    parts = [BANNER.format(source="templates.yml")]
    parts.append(f"# {t['title']}\n")

    # Status pill, plus review metadata where a page carries it. Time-sensitive
    # pages say when they were last checked, so a reader can judge staleness
    # rather than assume currency.
    meta = [status_pill(t["status"])]
    if t.get("version"):
        meta.append(f'<span class="gk-meta">v{t["version"]}</span>')
    if t.get("reviewed"):
        meta.append(
            f'<span class="gk-meta">Last reviewed <strong>{t["reviewed"]}</strong></span>'
        )
    parts.append(" &nbsp;·&nbsp; ".join(meta) + "\n")

    if t["status"] == "stub":
        parts.append(
            snippets["stub_invite"].format(contributing=rel_link(path, "contributing.md"))
        )
    elif t["status"] == "draft":
        parts.append(
            snippets["draft_note"].format(contributing=rel_link(path, "contributing.md"))
        )

    # Download buttons. build_downloads.py writes one .docx per template and a
    # .xlsx for anything in spreadsheets.yml; these links must match its output.
    dl = rel_link(path, "downloads/x").rsplit("/", 1)[0]
    buttons = [
        f'[:material-file-word: Word]({dl}/{t["id"]}.docx)'
        '{ .md-button .gk-dl download }'
    ]
    if t["id"] in SPREADSHEET_IDS:
        buttons.append(
            f'[:material-file-excel: Excel]({dl}/{t["id"]}.xlsx)'
            '{ .md-button .gk-dl download }'
        )
    buttons.append(
        f'[:material-language-markdown: Markdown]({dl}/{t["id"]}.md.txt)'
        f'{{ .md-button .gk-dl download="{t["id"]}.md" }}'
    )
    parts.append('<div class="gk-downloads" markdown>\n'
                 + "\n".join(buttons) + "\n</div>\n")

    ex = EXAMPLE_OF.get(t["id"])
    if ex:
        parts.append(
            f'!!! example "See this filled in"\n'
            f"    A [worked example]({rel_link(path, ex['path'])}) shows this\n"
            f"    template completed for a fictional mid-size company.\n"
        )

    parts.append(f"**Purpose.** {resolve_links(t['purpose'].strip(), path, by_id)}\n")
    parts.append(f"**When to use it.** {resolve_links(t['when_to_use'].strip(), path, by_id)}\n")
    parts.append(f"**How to use it.** {resolve_links(t['how_to_use'].strip(), path, by_id)}\n")

    # Which assessment questions this template answers — generated, so adding a
    # question automatically surfaces it on the pages that fix it.
    related_qs = [q for q in questions if t["id"] in q.get("templates", [])]
    if related_qs:
        qlist = ", ".join(f"**{q['id']}**" for q in related_qs[:8])
        parts.append(
            f"!!! tip \"Closes assessment gaps\"\n"
            f"    This template addresses {qlist} in the "
            f"[readiness assessment]({rel_link(path, 'assess/index.md')}).\n"
        )

    parts.append("---\n")
    parts.append("## The template\n")

    if t.get("generate_body") == "checklist":
        parts.append(build_checklist_body(questions, by_id, path))
    else:
        parts.append(resolve_links(t["body"].rstrip(), path, by_id) + "\n")

    parts.append("---\n")
    parts.append("## Adaptation notes\n")
    for note in t["adaptation"]:
        body = resolve_links(note["note"].strip(), path, by_id)
        parts.append(f"- **{note['context']}:** {body}")
    parts.append("")

    related = [by_id[r] for r in t.get("related", []) if r in by_id]
    if related:
        parts.append("## Related\n")
        for r in related:
            parts.append(
                f"- [{r['title']}]({rel_link(path, r['path'])}) "
                f"— {status_pill(r['status'])}"
            )
        parts.append("")

    parts.append(snippets["not_legal_advice"])
    return "\n".join(parts)


def render_example_page(ex: dict, company: dict, by_id: dict) -> str:
    """A worked example: the same template, filled in for the fictional company."""
    path = ex["path"]
    tpl = by_id[ex["of"]]
    parts = [BANNER.format(source="examples.yml")]
    parts.append(f"# {ex['title']}\n")
    parts.append(
        f'!!! info "A worked example, not a template"\n'
        f"    This shows {company['name']} — a fictional company — using the\n"
        f"    [{tpl['title']}]({rel_link(path, tpl['path'])}). To start your own,\n"
        f"    use the blank template. Details here are illustrative.\n"
    )
    parts.append(resolve_links(ex["intro"].strip(), path, by_id) + "\n")
    parts.append("---\n")
    parts.append(resolve_links(ex["body"].rstrip(), path, by_id) + "\n")
    parts.append("---\n")
    parts.append("## What to take from this\n")
    for t_ in ex["takeaways"]:
        parts.append(f"- {resolve_links(' '.join(t_.split()), path, by_id)}")
    parts.append("")
    parts.append(
        f"[Use the blank {tpl['title']}]({rel_link(path, tpl['path'])})"
        "{ .md-button .md-button--primary }\n"
    )
    parts.append(SNIPPETS_CACHE["not_legal_advice"])
    return "\n".join(parts)


def render_examples_index(examples: list, company: dict, by_id: dict) -> str:
    path = "examples/index.md"
    parts = [BANNER.format(source="examples.yml")]
    parts.append("# Worked examples\n")
    parts.append(
        "Blank templates tell you what to fill in; they do not tell you what "
        "*good* looks like, or how much detail is expected. These are the same "
        "templates completed for one fictional company, so you can see the "
        "level of detail that makes an artefact defensible.\n"
    )
    parts.append(
        '!!! tip "Deliberately imperfect"\n'
        "    These examples include an amber board pack, a risk being tolerated,\n"
        "    a control that was failing in practice, and an outstanding action\n"
        "    past its owner. A worked example where everything is green teaches\n"
        "    nothing.\n"
    )
    parts.append(f"## {company['name']}\n")
    parts.append(company["profile"].rstrip() + "\n")
    parts.append("## The examples\n")
    parts.append("| Worked example | Illustrates |")
    parts.append("|---|---|")
    for ex in examples:
        tpl = by_id[ex["of"]]
        parts.append(
            f"| [{ex['title']}]({rel_link(path, ex['path'])}) "
            f"| [{tpl['title']}]({rel_link(path, tpl['path'])}) |"
        )
    parts.append("")
    parts.append(SNIPPETS_CACHE["not_legal_advice"])
    return "\n".join(parts)


def render_tasks_page(tasks: list, by_id: dict) -> str:
    """The "I've been asked to…" index.

    Most people arrive with a request from someone else, not a browsing intent.
    This maps the ask, in the words it usually arrives in, to a starting order.
    """
    path = "tasks.md"
    parts = [BANNER.format(source="tasks.yml")]
    parts.append("# I've been asked to…\n")
    parts.append(
        "Most people land here because someone asked them for something. Find "
        "the request below and start where it points.\n"
    )
    parts.append(
        SNIPPET_ASSESS.format(assess=rel_link(path, "assess/index.md"))
    )
    for t in tasks:
        parts.append(f'## "{t["ask"]}"\n')
        parts.append(
            f"**Usually asked by:** {t['who']}  \n"
            f"**Rough effort:** {t['effort']}\n"
        )
        parts.append("**Start here, in this order:**\n")
        for n, tid in enumerate(t["start"], start=1):
            tpl = by_id.get(tid)
            if tpl is None:
                raise SystemExit(
                    f"ERROR: task {t['ask']!r} references unknown template '{tid}'"
                )
            parts.append(
                f"{n}. [{tpl['title']}]({rel_link(path, tpl['path'])})"
                f" — {' '.join(tpl['purpose'].split())[:110].rsplit(' ', 1)[0]}…"
            )
        parts.append("")
        parts.append(
            f'!!! tip "Before you start"\n'
            f"    {' '.join(t['note'].split())}\n"
        )
    parts.append(SNIPPETS_CACHE["not_legal_advice"])
    return "\n".join(parts)


def render_markdown_download(t: dict, by_id: dict, questions: list) -> str:
    """The template as standalone Markdown, for pasting into a wiki.

    Cross-references become plain template names rather than relative links,
    since those links would be broken once the file leaves the site.
    """
    def plain(text):
        return re.sub(
            r"\{\{([a-z0-9\-]+)\}\}",
            lambda m: by_id[m.group(1)]["title"] if m.group(1) in by_id else m.group(1),
            text or "",
        )

    out = [f"# {t['title']}\n"]
    out.append(f"**Purpose.** {plain(' '.join(t['purpose'].split()))}\n")
    out.append(f"**When to use it.** {plain(' '.join(t['when_to_use'].split()))}\n")
    out.append(f"**How to use it.** {plain(' '.join(t['how_to_use'].split()))}\n")
    out.append("---\n")

    if t.get("generate_body") == "checklist":
        items = sorted([q for q in questions if q.get("checklist")],
                       key=lambda q: q["checklist"])
        current = None
        for q in items:
            if q["category"] != current:
                current = q["category"]
                out.append(f"\n## {current}\n")
            out.append(f"- [ ] **{q['checklist']}.** {q['text']}")
            out.append(f"      *{' '.join(q['help'].split())}*")
            if q.get("evidence"):
                out.append(f"      **Evidence:** {' '.join(q['evidence'].split())}")
            out.append("")
        out.append("")
    else:
        # Admonitions are MkDocs-specific; flatten them to blockquotes so the
        # file renders sensibly in GitHub, Notion, Confluence, and plain editors.
        body = plain(t["body"].rstrip())
        lines, flat = body.split("\n"), []
        i = 0
        while i < len(lines):
            m = re.match(r'^!!!\s+\w+\s*"?([^"]*)"?\s*$', lines[i].strip())
            if m:
                flat.append(f"> **{m.group(1).strip() or 'Note'}**")
                i += 1
                while i < len(lines) and (not lines[i].strip()
                                          or lines[i].startswith("    ")):
                    if lines[i].strip():
                        flat.append("> " + lines[i].strip())
                    i += 1
                flat.append("")
                continue
            flat.append(lines[i])
            i += 1
        out.append("\n".join(flat) + "\n")

    out.append("---\n")
    out.append("## Adaptation notes\n")
    for note in t["adaptation"]:
        out.append(f"- **{note['context']}:** {plain(' '.join(note['note'].split()))}")
    out.append("")
    out.append("---\n")
    out.append(
        "*From the [Open Data & AI Governance Kit]"
        "(https://lsdeva.github.io/governance-kit/). Licensed "
        "[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) — free to use, "
        "adapt, and share with attribution.*\n"
    )
    out.append(
        "***Not legal advice.** Adapt to your jurisdiction, sector, and risk "
        "appetite, and have qualified counsel review anything material.*\n"
    )
    return "\n".join(out)


def render_section_index(section: dict, templates: list, by_id: dict) -> str:
    path = f"{section['id']}/index.md"
    parts = [BANNER.format(source="sections.yml + templates.yml")]
    parts.append(f"# {section['title']}\n")
    parts.append(section["blurb"].strip() + "\n")
    parts.append("| Template | Status | Purpose |")
    parts.append("|---|---|---|")
    for t in templates:
        purpose = " ".join(t["purpose"].split())
        if len(purpose) > 155:
            purpose = purpose[:152].rsplit(" ", 1)[0] + "…"
        parts.append(
            f"| [{t['title']}]({rel_link(path, t['path'])}) "
            f"| {status_pill(t['status'])} | {purpose} |"
        )
    parts.append("")
    parts.append(
        SNIPPET_ASSESS.format(assess=rel_link(path, "assess/index.md"))
    )
    return "\n".join(parts)


SNIPPET_ASSESS = ""  # filled from snippets.yml at runtime
SNIPPETS_CACHE = {}  # ditto; used by the example renderers
EXAMPLE_OF = {}      # template id -> worked example, for the "see it filled in" link


def build_assessment_json(roles, questions, templates, sections) -> dict:
    """The single JSON payload the /assess/ app fetches.

    Template links are pre-resolved to paths relative to docs/assess/ so the
    browser never has to know the site structure.
    """
    by_id = {t["id"]: t for t in templates}

    tpl_out = {}
    for t in templates:
        tpl_out[t["id"]] = {
            "id": t["id"],
            "title": t["title"],
            "section": t["section"],
            "status": t["status"],
            "url": rel_link("assess/index.md", t["path"]).replace(".md", "/"),
            "purpose": " ".join(t["purpose"].split()),
        }

    q_out = []
    for q in questions:
        missing = [t for t in q.get("templates", []) if t not in by_id]
        if missing:
            raise SystemExit(f"ERROR: {q['id']} references unknown template(s): {missing}")
        q_out.append(
            {
                "id": q["id"],
                "text": q["text"],
                "help": " ".join(q["help"].split()),
                "evidence": " ".join((q.get("evidence") or "").split()),
                "category": q["category"],
                "roles": q["applies_to"],
                "weight": q["weight"],
                "templates": q.get("templates", []),
                "obligation": q.get("obligation", {}),
                "checklist": q.get("checklist"),
            }
        )

    role_ids = {r["id"] for r in roles}
    for q in questions:
        unknown = [r for r in q["applies_to"] if r not in role_ids]
        if unknown:
            raise SystemExit(f"ERROR: {q['id']} references unknown role(s): {unknown}")

    return {
        "version": 1,
        "roles": [
            {
                "id": r["id"],
                "name": r["name"],
                "short": " ".join(r["short"].split()),
                "focus": r.get("focus", []),
                "questionCount": sum(1 for q in questions if r["id"] in q["applies_to"]),
            }
            for r in roles
        ],
        "questions": q_out,
        "templates": tpl_out,
        "categories": CATEGORY_ORDER,
        "bands": BANDS,
        "sections": {s["id"]: s["title"] for s in sections},
    }


def build_nav(sections, templates, examples, tasks) -> str:
    lines = [NAV_START, "nav:", "  - Home: index.md", "  - Get started: getting-started.md",
             "  - Assessment: assess/index.md"]
    if tasks:
        lines.append("  - I've been asked to…: tasks.md")
    for s in sections:
        lines.append(f"  - {s['nav']}:")
        lines.append(f"      - Overview: {s['id']}/index.md")
        for t in templates:
            if t["section"] == s["id"]:
                lines.append(f"      - {t.get('nav', t['title'])}: {t['path']}")
    if examples:
        lines.append("  - Worked examples:")
        lines.append("      - Overview: examples/index.md")
        for e in examples:
            lines.append(f"      - {e.get('nav', e['title'])}: {e['path']}")
    lines.append("  - Contributing: contributing.md")
    lines.append("  - About: about.md")
    lines.append(NAV_END)
    return "\n".join(lines)


def write(path: Path, content: str, written: list, check: bool) -> None:
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == content:
        return
    if check:
        written.append(path)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    written.append(path)


def main() -> int:
    global SNIPPET_ASSESS

    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report stale files without writing; exit 1 if any")
    args = ap.parse_args()

    sections = load("sections.yml")
    roles = load("roles.yml")
    questions = load("questions.yml")
    templates = load("templates.yml")
    snippets = load("snippets.yml")

    SNIPPET_ASSESS = snippets["assess_callout"]
    SNIPPETS_CACHE.update(snippets)
    SPREADSHEET_IDS.update((load("spreadsheets.yml") or {}).keys())

    examples_data = load("examples.yml") or {}
    company = examples_data.get("company", {})
    examples = examples_data.get("examples", [])
    EXAMPLE_OF.update({e["of"]: e for e in examples})

    by_id = {t["id"]: t for t in templates}

    # ---- integrity checks: fail loudly rather than generating a broken site --
    dupes = [i for i, c in Counter(t["id"] for t in templates).items() if c > 1]
    if dupes:
        raise SystemExit(f"ERROR: duplicate template ids: {dupes}")

    section_ids = {s["id"] for s in sections}
    for t in templates:
        if t["section"] not in section_ids:
            raise SystemExit(f"ERROR: {t['id']} has unknown section '{t['section']}'")
        if t["status"] not in STATUS_LABELS:
            raise SystemExit(f"ERROR: {t['id']} has unknown status '{t['status']}'")
        for r in t.get("related", []):
            if r not in by_id:
                raise SystemExit(f"ERROR: {t['id']} relates to unknown template '{r}'")

    qdupes = [i for i, c in Counter(q["id"] for q in questions).items() if c > 1]
    if qdupes:
        raise SystemExit(f"ERROR: duplicate question ids: {qdupes}")
    for q in questions:
        if q["category"] not in CATEGORY_ORDER:
            raise SystemExit(f"ERROR: {q['id']} has unknown category '{q['category']}'")
        if not 1 <= q["weight"] <= 5:
            raise SystemExit(f"ERROR: {q['id']} weight {q['weight']} outside 1-5")
        if not q["applies_to"]:
            raise SystemExit(f"ERROR: {q['id']} applies to no roles")
        if not q.get("evidence"):
            raise SystemExit(
                f"ERROR: {q['id']} has no `evidence:`. Every question must say "
                "what would satisfy an auditor, or the exported report cannot "
                "double as an evidence list."
            )

    cl = [q["checklist"] for q in questions if q.get("checklist")]
    if sorted(cl) != list(range(1, len(cl) + 1)):
        raise SystemExit(f"ERROR: checklist numbers must be 1..N with no gaps; got {sorted(cl)}")

    for r in roles:
        n = sum(1 for q in questions if r["id"] in q["applies_to"])
        if n < 5:
            raise SystemExit(f"ERROR: role '{r['id']}' has only {n} questions (minimum 5)")

    for e in examples:
        if e["of"] not in by_id:
            raise SystemExit(f"ERROR: example '{e['id']}' illustrates unknown template '{e['of']}'")
    ex_dupes = [i for i, c in Counter(e["of"] for e in examples).items() if c > 1]
    if ex_dupes:
        raise SystemExit(f"ERROR: more than one example for template(s): {ex_dupes}")

    written: list[Path] = []

    # ---- template pages -----------------------------------------------------
    for t in templates:
        write(DOCS / t["path"],
              render_template_page(t, by_id, snippets, questions), written, args.check)
        # Raw Markdown download: the template on its own, without site chrome or
        # cross-page links, ready to paste into a wiki or an internal doc.
        #
        # Written with a .md.txt extension because MkDocs treats any .md file
        # under docs/ as a page to render — a plain .md here would be served as
        # HTML, so the "Markdown" button would hand back the wrong thing.
        write(DOCS / "downloads" / (t["id"] + ".md.txt"),
              render_markdown_download(t, by_id, questions), written, args.check)

    # ---- section index pages ------------------------------------------------
    for s in sections:
        in_section = [t for t in templates if t["section"] == s["id"]]
        write(DOCS / s["id"] / "index.md",
              render_section_index(s, in_section, by_id), written, args.check)

    # ---- generated stats snippet -------------------------------------------
    # Counts injected into hand-written pages, so a claim like "25 of 26 fully
    # drafted" cannot drift from what the data actually says.
    # Written to the repo root, not docs/, because any .md under docs/ becomes
    # a page. pymdownx.snippets pulls it into the landing page.
    n_ready = sum(1 for t in templates if t["status"] == "ready")
    stats = (
        f"{len(templates)} templates · **{n_ready} of {len(templates)} fully "
        f"drafted** · {len(questions)} assessment questions across "
        f"{len(roles)} roles · {len(examples)} worked examples\n"
    )
    write(ROOT / "snippets" / "stats.md", stats, written, args.check)

    # ---- task index ---------------------------------------------------------
    tasks = load("tasks.yml") or []
    if tasks:
        write(DOCS / "tasks.md", render_tasks_page(tasks, by_id), written, args.check)

    # ---- worked examples ----------------------------------------------------
    if examples:
        write(DOCS / "examples" / "index.md",
              render_examples_index(examples, company, by_id), written, args.check)
        for e in examples:
            write(DOCS / e["path"],
                  render_example_page(e, company, by_id), written, args.check)

    # ---- assessment data ----------------------------------------------------
    payload = build_assessment_json(roles, questions, templates, sections)
    write(DOCS / "assess" / "assessment-data.json",
          json.dumps(payload, indent=2, ensure_ascii=False) + "\n", written, args.check)

    # ---- navigation in mkdocs.yml ------------------------------------------
    mk = ROOT / "mkdocs.yml"
    text = mk.read_text(encoding="utf-8")
    nav = build_nav(sections, templates, examples, tasks)
    if NAV_START in text and NAV_END in text:
        new_text = re.sub(
            re.escape(NAV_START) + r".*?" + re.escape(NAV_END),
            nav.replace("\\", "\\\\"),
            text,
            flags=re.S,
        )
    else:
        new_text = re.sub(r"\nnav:\n(?:.*\n)*?\Z", "\n" + nav + "\n", text)
    if new_text != text:
        if not args.check:
            mk.write_text(new_text, encoding="utf-8", newline="\n")
        written.append(mk)

    # ---- report -------------------------------------------------------------
    if args.check:
        if written:
            print("STALE — these files differ from the data files:")
            for p in written:
                print(f"  {p.relative_to(ROOT)}")
            print("\nRun: python tools/build_content.py")
            return 1
        print(f"Up to date: {len(templates)} templates, {len(questions)} questions, "
              f"{len(roles)} roles.")
        return 0

    print(f"Generated {len(templates)} template pages, {len(sections)} section indexes, "
          f"assessment data ({len(questions)} questions, {len(roles)} roles).")
    if written:
        print(f"Changed {len(written)} file(s).")
    else:
        print("No changes — already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
